name: npm publish when merge request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: update package version
        run: |
          npm version patch
          git config --global user.email "xinyu198736@gmail.com"
          git config --global user.name "xinyu198736"
          git add .
          git commit -m "Update package version"
          git push
      - name: npm install, build 
        run: |
          npm install
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 